name: Build Application

on:
  # merge requests to main will trigger a build or manual dispatch
  workflow_dispatch: 
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
      - run: zig build
